lo// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8OrjgH1QgZH3-CuUxSV1LiXqAwQyHhVw',
    appId: '1:59848967014:web:33f35ead196d3789397ea7',
    messagingSenderId: '59848967014',
    projectId: 'event-93268',
    authDomain: 'event-93268.firebaseapp.com',
    storageBucket: 'event-93268.appspot.com',
    measurementId: 'G-QGX0HVQZD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw3IKwrs4xhEgMpvGYeqD63ZzlHwTj_DM',
    appId: '1:59848967014:android:6810a95cf76c2f0d397ea7',
    messagingSenderId: '59848967014',
    projectId: 'event-93268',
    storageBucket: 'event-93268.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDawXDwfonbtat3NDuCwxIYj3yfsYMfZPg',
    appId: '1:59848967014:ios:0afe6197d4a6c7c7397ea7',
    messagingSenderId: '59848967014',
    projectId: 'event-93268',
    storageBucket: 'event-93268.appspot.com',
    iosBundleId: 'com.app.eventManagemenet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDawXDwfonbtat3NDuCwxIYj3yfsYMfZPg',
    appId: '1:59848967014:ios:54499b6eb17d5db9397ea7',
    messagingSenderId: '59848967014',
    projectId: 'event-93268',
    storageBucket: 'event-93268.appspot.com',
    iosBundleId: 'com.app.eventManagemenet.RunnerTests',
  );
}
